[package]
edition = "2021"
name = "blog-romira-dev"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ssr_hydrate"
required-features = ["hydration"]

[[bin]]
name = "ssr_server"
required-features = ["ssr"]

[dependencies]
bytes = "1.4.0"
dotenv = "0.15.0"
envy = "0.4.2"
futures = {version = "0.3.26"}
gloo = "0.8.0"
log = "0.4.17"
once_cell = "1.17.1"
reqwest = {version = "0.11.14", features = ["json"]}
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
strum_macros = "0.24.3"
uuid = {version = "1.3.0", features = ["serde"]}
yew = "0.20.0"
yew-hooks = "0.2.0"
yew-router = "0.17.0"
yewdux = "0.9.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.34"
wasm-logger = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = "0.5.17"
chrono = "0.4.23"
clap = {version = "4.1.6", features = ["derive"]}
hyper = {version = "0.14", features = ["server", "http1"]}
jemallocator = "0.5"
tokio = {version = "1.25.0", features = ["full"]}
tower = {version = "0.4.13", features = ["make"]}
tower-http = {version = "0.3.5", features = ["fs", "trace"]}
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features = ["env-filter", "json"]}

[features]
hydration = ["yew/hydration"]
ssr = ["yew/ssr"]
