[package]
edition = "2021"
name = "blog-romira-dev"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ssr_hydrate"
required-features = ["hydration"]

[[bin]]
name = "ssr_server"
required-features = ["ssr"]

[dependencies]
bytes = "1.0"
futures = {version = "0.3", features = ["std"], default-features = false}
gloo = "0.8.0"
log = "0.4"
reqwest = {version = "0.11.8", features = ["json"]}
serde = {version = "1.0.132", features = ["derive"]}
uuid = {version = "1.0.0", features = ["serde"]}
yew = "0.20.0"
yew-router = "0.17.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = "0.5"
clap = {version = "3.1.7", features = ["derive"]}
env_logger = "0.9"
hyper = {version = "0.14", features = ["server", "http1"]}
jemallocator = "0.5"
tokio = {version = "1.15.0", features = ["full"]}
tower = {version = "0.4", features = ["make"]}
tower-http = {version = "0.3", features = ["fs"]}

[features]
hydration = ["yew/hydration"]
ssr = ["yew/ssr"]
