name: Deploy to s3

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy_to_s3.yml"
      - "frontend/**"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BUCKET_NAME: "blog-romira-dev-static"
  AWS_REGION: "ap-northeast-1"

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-build
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./**/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('.github/workflows/deploy_to_s3.yml') }}-build

      - uses: actions-rs/toolchain@v1
        if: steps.cache-build.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install trunk
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - name: build
        run: |
          trunk build --release

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/blog-romira-dev-gha
          role-session-name: github-actions-deploy-session
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy to s3
        run: |
          aws s3 sync --delete --region ap-northeast-1 dist/ s3://${{ env.BUCKET_NAME }}

      # キャッシュパージ
      # - name: clear cache
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
